### ISSUE TITLE
Error openauth

### ISSUE THREAD

**Issue by MonkeyMoon104** [0WhiteDev/Minecraft-Cheat-Client-Base#1]
give me a error of openauth
![image](https://github.com/user-attachments/assets/5518586f-11eb-4994-9b45-1814cc3dee6c)

**Comment by 0WhiteDev** [comment]
Openauth jar is in libs folder, you can include it as follows:

- Go to Project Structure
- Go to Libraries
- Click +
- Select the “libs” folder
- Apply

or add it in maven dependencies

**Comment by MonkeyMoon104** [comment]
there is no a "Click +"[image: image.png]

Il giorno lun 2 set 2024 alle ore 23:25 0WhiteDev ***@***.***>
ha scritto:
